on: push
name: npm install, lint, test and deploy

jobs:
  build-and-publish:
    name: build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - run: npm install
      - run: npm run lint
      - run: npm run test
      - name: Publish to Docker Repository
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: anatoliche/node_rest_api_nofw
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          run: docker build -t back .
